import Head from "next/head";
import Navbar from "../components/layout/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen max-w-screen-2xl w-11/12 mx-auto px-2">
        <Navbar />
      </main>
    </div>
  );
}
